config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#welcome'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/bookuser/new', to: 'books#new_book_user'
  delete '/bookuser/:id', to: 'books#destroy_book_user'

  post '/books/:book_id/articles/:article_id/lock', to: 'articles#switch_is_locked'
  post '/books/:book_id/public', to: 'books#switch_is_public'

  post '/books/:book_id/articles/:article_id/upload_image', to: 'articles#upload_image', as: :upload_image
  post '/books/:book_id/articles/:article_id/images/:image_id/remove', to: 'articles#remove_image'

  get '/search', to: 'search#index'

  resources :users

  resources :books do
    resources :articles
  end

  get '/books/:book_id/articles/:parent_id/new', to: 'articles#new_subarticle'
  get '/books/:book_id/articles/:article_id/download', to: 'articles#download_deck'
end

app/models/article.rb
class Article < ApplicationRecord
  ANKI_NOTE_REGEX = /\[\[(.*?)\]\]/

  belongs_to :book
  has_many :children, class_name: "Article", foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: "Article", foreign_key: 'parent_id', optional: true

  validates :name, presence: true
  validates :content, presence: true

  has_many_attached :images

  def subarticles
    subarticles = Article.where(parent_id: self.id)
  end

  def has_children?
    subarticles.count != 0
  end

  def to_s
    "==Article #{self.id}: name: #{self.name}; content: #{self.content}; is_locked: #{self.is_locked}=="
  end

  # returns a list of the raw content of the Anki notes of the article
  # for example if the article has [[This is an {{c1::Anki note}}.]]
  # then the return value would be ['This is an {{c1::Anki note}}.']
  def raw_anki_notes
    matches = self.content.scan(ANKI_NOTE_REGEX)
    raw_notes = matches.map { |match| match[0] }
  end

  # returns parent article or nil
  def parent
    Article.find_by(id: self.parent_id)
  end

  # returns the corresponding anki deck title string to the article
  # in anki, a parent deck "deck" with child deck "child" would be
  # string "deck::child" and this method makes deck titles like these
  def anki_deck_title
    title = self.name
    current_article = self
    while current_article.parent
      title = current_article.parent.name + '::' + title
      current_article = current_article.parent
    end
    'AnkiBooks::' + title
  end

  def to_json_data
    my_hash = { title: anki_deck_title, notes: raw_anki_notes , images: [] }

    temp_folder = ActiveStorage::SendZipHelper.save_files_on_server(self.images)
    my_hash[:images_temp_folder_path] = temp_folder

    Dir.foreach(temp_folder) do |filename|
      next if filename == '.' || filename == '..'
      my_hash[:images] << filename.to_s
    end

    my_hash.to_json
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login, only: [:show, :download_deck]

  def new # GET /books/:book_id/articles/new
    @book = current_user.books.find_by(id: params[:book_id])
    @article = Article.new
  end

  def new_subarticle # GET /books/:book_id/articles/:parent_id/new
    @book = current_user.books.find_by(id: params[:book_id])
    @parent_article = @book.articles.find(params[:parent_id])
    @article = Article.new
  end

  def show # GET /books/:book_id/articles/:id
    user = current_user
    @book = Book.find_by(id: params[:book_id])
    @article = @book.articles.find(params[:id])
    if !user && !@book.is_public
      redirect_to "/"
    elsif user && !@book.is_public && !user.books.include?(@book)
      redirect_to "/"
    else
      render json: @article
    end
  end

  def create #  POST /books/:book_id/articles
    user = current_user
    @book = user.books.find_by(id: params[:book_id])
    @article = @book.articles.new(article_params)
    if !user.can_edit?(@book)
      flash[:error] = "You cannot add an article to this book."
      redirect_to books_path
    elsif @article.save
      flash[:success] = "Article successfully created."
      redirect_to edit_book_path(@book)
    else
      if article_params[:parent_id]
        @parent_article = @book.articles.find(article_params[:parent_id])
        render :new_subarticle, status: :unprocessable_entity
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit # GET /books/:book_id/articles/:id/edit
    @user = current_user
    @book = current_user.books.find_by(id: params[:book_id])
    @article = @book.articles.find(params[:id])
    @parent_article = @article.parent
    @should_show_upload_image_button = true
    if @article.is_locked
      flash[:error] = 'You cannot edit a locked article.'
      redirect_to edit_book_path(@book)
    end
  end

  def update # PATCH /books/:book_id/articles/:id
    user = current_user
    @book = user.books.find_by(id: params[:book_id])
    @article = @book.articles.find(params[:id])
    if @article.is_locked
      flash[:error] = 'You cannot update a locked article.'
      redirect_to edit_book_path(@book)
    elsif !user.can_edit?(@book)
      flash[:error] = "You cannot update the articles of this book."
      redirect_to books_path
    elsif @article.update(article_params)
      flash[:success] = "Article successfully updated."
      redirect_to edit_book_article_path(@book, @article)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy # DELETE /books/:book_id/articles/:id
    user = current_user
    book = user.books.find(params[:book_id])
    article = book.articles.find(params[:id])
    if user.can_edit?(book)
      article.destroy
      flash[:success] = "Article successfully deleted."
    else
      # raise the same error as if the book couldnt be found
      raise ActiveRecord::RecordNotFound
    end
    redirect_to edit_book_path(book), status: :see_other
  end

  def switch_is_locked # POST /books/:book_id/articles/:article_id/lock
    user = current_user
    book = user.books.find(params[:book_id])
    article = book.articles.find(params[:article_id])
    if user.owns_book?(book)
      article.is_locked = !article.is_locked
      article.save
      flash[:success] = 'Article successfully locked.' if article.is_locked
      flash[:success] = 'Article successfully unlocked.' unless article.is_locked
    else
      flash[:error] = 'You do not have permission to lock/unlock articles of this book.'
    end
    redirect_to edit_book_path(book), status: :see_other
  end

  def download_deck # GET /books/:book_id/articles/:article_id/download
    user = current_user
    book = Book.find_by(id: params[:book_id])
    article = Article.find_by(id: params[:article_id])
    data_json = article.to_json_data

    if !user && !book.is_public
      flash[:error] = "You cannot download a deck from a private book while not logged in."
      redirect_to "/"
    elsif user && !book.is_public && !user.books.include?(book)
      flash[:error] = "You cannot download a deck from a private book you do not have access to."
      redirect_to "/"
    else
      where_to_put_decks = Rails.root.join('storage')
      deck_filename = `python3 lib/assets/python/make_deck.py '#{data_json}' '#{where_to_put_decks}'`
      file_to_download = File.join(where_to_put_decks, deck_filename)

      if File.exist?(file_to_download)
        send_file file_to_download, filename: deck_filename
      else
        flash[:error] = 'Failed to generate Anki deck.'
        redirect_to book
      end
    end
  end

  def upload_image # POST /books/:book_id/articles/:article_id/upload_image
    user = current_user
    book = user.books.find(params[:book_id])
    article = book.articles.find(params[:article_id])
    begin
      image = params[:article][:image]
      file_extension = File.extname(File.path(image.tempfile))
      if file_extension == '.png' || file_extension == '.jpg'
        article.images.attach(image)
        flash[:success] = "Image successfully uploaded."
      else
        flash[:error] = "Only .png and .jpg images may be uploaded."
      end
    rescue
      flash[:error] = "Something went wrong uploading an image."
    end
    redirect_to edit_book_article_path(book, article)
  end

  def remove_image # POST /books/:book_id/articles/:article_id/images/:image_id/remove
    user = current_user
    book = user.books.find(params[:book_id])
    article = book.articles.find(params[:article_id])
    image = ActiveStorage::Attachment.find(params[:image_id])
    if article.images.include?(image)
      image.purge
      flash[:success] = "Image successfully removed from article."
    else
      flash[:error] = "Something went wrong removing image from article."
    end
    redirect_to edit_book_article_path(book, article)
  end

  private

  def article_params
    params.require(:article).permit(:name, :content, :parent_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<style>
.article-content-displayed h1, .article-content-displayed h2, .article-content-displayed h3, .article-content-displayed h4, .article-content-displayed h5, .article-content-displayed h6 {
  font-weight: 500;
  border-bottom: 1px solid gray;
}
.article-content-displayed h1 {
  font-size: 2.5rem;
}
.article-content-displayed h2 {
  font-size: 2.25rem;
}
.article-content-displayed h3 {
  font-size: 2rem;
}
.article-content-displayed h4 {
  font-size: 1.75rem;
}
.article-content-displayed h5 {
  font-size: 1.5rem;
}
.article-content-displayed h6 {
  font-size: 1.25rem;
}
.article-content-displayed .ankiNote {
  font-weight: 350;
}
.article-content-displayed img {
  padding: 1rem;
  margin: auto;
}
.article-content-displayed p {
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
}
</style>


<div class="lg:grid lg:grid-cols-2 lg:h-screen">
  <section>
  <h1 class="p-4 text-2xl"><%= title %></h1>
    <%= form_with model: [@book, @article], class: "px-4" do |f| %>

      <% if @article.errors.any? %>
        <div>
          This form contains <%= pluralize(@article.errors.count, "error") %>.
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="flex justify-between items-center">
        <div>
          <%= f.label :name, class: "block" %>
          <%= f.text_field :name, class: "block" %>
        </div>
        <div>
          <%= f.submit class: "p-2 text-sm bg-blue-600 text-white rounded-md shadow-md hover:bg-blue-700 hover:shadow-lg" %>
          <% if @should_show_upload_image_button %>
            <button id="show-upload-image-modal-button" class="p-2 text-sm bg-blue-600 text-white rounded-md shadow-md hover:bg-blue-700 hover:shadow-lg">Upload Image</button>
          <% end %>
          <button id="update-preview-button" class="p-2 text-sm bg-blue-600 text-white rounded-md shadow-md hover:bg-blue-700 hover:shadow-lg">Update Preview</button>
        </div>
      </div>
      

      <%= f.label :content, class: "block" %>

      <div class="bg-white flex justify-start border-b">
        <button id="header-1-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-type-h1" viewBox="0 0 16 16">
            <path d="M8.637 13V3.669H7.379V7.62H2.758V3.67H1.5V13h1.258V8.728h4.62V13h1.259zm5.169 0V3.669h-1.244L10.5 5.316v1.265l2.16-1.565h.062V13h1.244z"/>
          </svg>
        </button>

        <button id="header-2-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-type-h2" viewBox="0 0 16 16">
            <path d="M7.638 13V3.669H6.38V7.62H1.759V3.67H.5V13h1.258V8.728h4.62V13h1.259zm3.022-6.733v-.048c0-.889.63-1.668 1.716-1.668.957 0 1.675.608 1.675 1.572 0 .855-.554 1.504-1.067 2.085l-3.513 3.999V13H15.5v-1.094h-4.245v-.075l2.481-2.844c.875-.998 1.586-1.784 1.586-2.953 0-1.463-1.155-2.556-2.919-2.556-1.941 0-2.966 1.166-2.966 2.74v.049h1.223z"/>
          </svg>
        </button>

        <button id="header-3-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-type-h3" viewBox="0 0 16 16">
            <path d="M7.637 13V3.669H6.379V7.62H1.758V3.67H.5V13h1.258V8.728h4.62V13h1.259zm3.625-4.272h1.018c1.142 0 1.935.67 1.949 1.674.013 1.005-.78 1.737-2.01 1.73-1.08-.007-1.853-.588-1.935-1.16H9.108c.069 1.167 1.224 2.386 3.083 2.386 1.935 0 3.343-1.155 3.309-2.789-.027-1.51-1.251-2.16-2.037-2.249v-.068c.704-.123 1.764-.91 1.723-2.229-.035-1.353-1.176-2.4-2.954-2.385-1.873.006-2.857 1.162-2.898 2.358h1.196c.062-.69.711-1.299 1.696-1.299.998 0 1.695.622 1.695 1.525.007.922-.718 1.592-1.695 1.592h-.964v1.074z"/>
          </svg>
        </button>

        <button id="italicize-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-type-italic" viewBox="0 0 16 16">
            <path d="M7.991 11.674 9.53 4.455c.123-.595.246-.71 1.347-.807l.11-.52H7.211l-.11.52c1.06.096 1.128.212 1.005.807L6.57 11.674c-.123.595-.246.71-1.346.806l-.11.52h3.774l.11-.52c-1.06-.095-1.129-.211-1.006-.806z"/>
          </svg>
        </button>

        <button id="bold-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-type-bold" viewBox="0 0 16 16">
            <path d="M8.21 13c2.106 0 3.412-1.087 3.412-2.823 0-1.306-.984-2.283-2.164-2.386v-.055a2.176 2.176 0 0 0 1.852-2.14c0-1.51-1.162-2.46-3.014-2.46H3.843V13H8.21zM5.908 4.674h1.696c.963 0 1.517.451 1.517 1.244 0 .834-.629 1.16-1.73 1.16H5.908V4.673zm0 6.788V8.598h1.73c1.217 0 1.88.492 1.88 1.415 0 .943-.643 1.449-1.816 1.449H5.907z"/>
          </svg>
        </button>

        <button id="code-button" class="hover:bg-gray-200 p-4">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-code" viewBox="0 0 16 16">
            <path d="M5.854 4.854a.5.5 0 1 0-.708-.708l-3.5 3.5a.5.5 0 0 0 0 .708l3.5 3.5a.5.5 0 0 0 .708-.708L2.707 8l3.147-3.146zm4.292 0a.5.5 0 0 1 .708-.708l3.5 3.5a.5.5 0 0 1 0 .708l-3.5 3.5a.5.5 0 0 1-.708-.708L13.293 8l-3.147-3.146z"/>
          </svg>
        </button>

        <button id="c1-button" class="hover:bg-gray-200 p-1">
          {{c1::}}
        </button>

        <button id="c2-button" class="hover:bg-gray-200 p-1">
          {{c2::}}
        </button>

        <button id="anki-note-button" class="hover:bg-gray-200 p-2">
          [[ ]]
        </button>

      </div>

      <%= f.text_area :content, class: "block w-full h-96 min-h-full resize-none", id: "markdown-editor" %>

      <%= f.hidden_field :parent_id, value: "#{@parent_article ? @parent_article.id : nil}" %>

    <% end %>
  </section>

  
  <section id="preview" class="article-content-displayed bg-white border border-black shadow-md rounded-md m-4 p-4 overflow-y-scroll">
    
  </section>
  
</div>

<% if @should_show_upload_image_button %>
  <%= render partial: "upload_image_form", layout: "shared/modal", locals: {label: "upload-image"} %>
<% end %>

app/views/articles/_upload_image_form.html.erb
<%= form_with url: upload_image_path(@book, @article), method: :post, model: @article do |f| %>

  <p><strong>Note that uploading an image will reload the page.</strong></p>
  <p>Any changes made to the content of the article since the last update will be lost.</p>

  <%= f.file_field :image %>

  <%= f.submit "Upload image", class: "bg-blue-600 p-2 text-white rounded-md cursor-pointer mt-4", id: "upload-image-button" %>

<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'form', locals: {title: "Editing Article: #{@article.name}"} %>

<% if @article.images.count != 0 %>
  <section class="p-4">
  <h2 class="text-xl">Images available to this article:</h2>
  <div class="flex flex-wrap">

    <% @article.images.each do |image| %>
    <div class="flex items-center p-4 m-4 border-black border">

      <%= image_tag image.representation(resize_to_limit: [150, 150]) %>

      <div class="flex flex-col justify-around h-full items-center pl-4">

        <button id="![Alternative text](<%= url_for(image) %>)" class="copy-image-link-buttons bg-blue-600 text-white text-xs p-1 rounded-md">Copy Markdown</button>

        <form method="post" action="/books/<%= @book.id %>/articles/<%= @article.id %>/images/<%= image.id %>/remove">
          <button type="submit" class="bg-red-600 text-white text-xs p-1 rounded-md">Remove Image</button>
        </form>

      </div>
      
    </div>
    <% end %>

  </section>
<% end %>

<div class="mt-8 flex justify-between p-4">
  <%= link_to "Back", edit_book_path(@book), class: "bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2" %>
  <%= link_to "Delete article", book_article_path(@book, @article), class: "p-2 bg-red-600 text-white rounded-md", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</div>

app/views/articles/new.html.erb
<%= render partial: 'form', locals: {title: "New Article"} %>

app/views/articles/new_subarticle.html.erb
<%= render partial: 'form', locals: {title: "New subarticle for article: '#{@parent_article.name}'"} %>