config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#welcome'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post '/bookuser/new', to: 'books#new_book_user'
  delete '/bookuser/:id', to: 'books#destroy_book_user'

  post '/books/:book_id/articles/:article_id/lock', to: 'articles#switch_is_locked'
  post '/books/:book_id/public', to: 'books#switch_is_public'

  post '/books/:book_id/articles/:article_id/upload_image', to: 'articles#upload_image', as: :upload_image
  post '/books/:book_id/articles/:article_id/images/:image_id/remove', to: 'articles#remove_image'

  get '/search', to: 'search#index'

  resources :users

  resources :books do
    resources :articles
  end

  get '/books/:book_id/articles/:parent_id/new', to: 'articles#new_subarticle'
  get '/books/:book_id/articles/:article_id/download', to: 'articles#download_deck'
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_users
  has_many :users, through: :book_users

  has_many :articles

  validates :name, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :description, presence: true, length: { maximum: 250 }

  def top_level_articles
    self.articles.select do |article|
      article.parent_id.nil?
    end
  end

  # returns the role (as a string) for the book and user
  def role(user)
    role_id = self.book_users.where("user_id = #{user.id}").first.role_id
    case role_id
    when 1
      'owner'
    when 2
      'editor'
    when 3
      'reader'
    end
  end

  def to_s
    "==Book #{self.id}: name: #{self.name}; description: #{self.description}; is_public: #{self.is_public}=="
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :require_login, only: [:show]

  def index # GET /books
    @user = current_user
    @books = @user.books
  end

  def new # GET /books/new
    @book = Book.new
  end

  def edit # GET /books/:id/edit
    @user = current_user
    @book = @user.books.find(params[:id])
    unless @user.can_edit?(@book)
      redirect_to books_path
    end
  end

  def update # PATCH /books/:id
    @user = current_user
    @book = @user.books.find(params[:id])
    if !@user.owns_book?(@book)
      flash[:error] = 'You cannot update this book.'
      redirect_to books_path
    elsif @user && @book.update(book_params)
      flash[:success] = "Book successfully updated."
      redirect_to edit_book_path(@book)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create # POST /books
    @book = Book.new(book_params)
    user = current_user
    if user && @book.save
      user.books << @book
      book_user = @book.book_users.where(["book_id = ? and user_id = ?", @book.id, user.id]).first
      book_user.role_id = 1
      book_user.save
      flash[:success] = "New book '#{@book.name}' created."
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show # GET /books/:id
    @user = current_user
    @book = Book.find_by(id: params[:id])
    if !@user && !@book.is_public
      redirect_to "/"
    elsif @user && !@book.is_public && !@user.books.include?(@book)
      redirect_to "/"
    end
  end

  def destroy # DELETE /books/:id
    user = current_user
    book = user.books.find(params[:id])
    if user.owns_book?(book)
      book.destroy
      flash[:success] = "Book successfully deleted."
    else
      # raise the same error as if the book couldnt be found
      raise ActiveRecord::RecordNotFound
    end
    redirect_to books_path, status: :see_other
  end

  def new_book_user # POST /bookuser/new
    user = current_user
    book = user.books.find(book_user_params[:book_id])
    user_book_was_shared_with = User.find_by(name: book_user_params[:name])
    role_id = book_user_params[:role_id].to_i
    if !user_book_was_shared_with
      flash[:error] = "User was not found; book not shared."
    elsif !user.owns_book?(book)
      flash[:error] = "You may not share a book that you do not own."
    elsif user_book_was_shared_with.books.include?(book)
      flash[:error] = "You cannot share a book with a user who already has the book."
    elsif (1..3).cover?(role_id)
      user_book_was_shared_with.books << book
      book_user = book.book_users.where(["book_id = ? and user_id = ?", book.id, user_book_was_shared_with.id]).first
      book_user.role_id = role_id
      book_user.save
      flash[:success] = "Book successfully shared with #{user_book_was_shared_with.name}"
    end
    redirect_to edit_book_path(book)
  end

  def destroy_book_user # DELETE /bookuser/:id
    user = current_user
    book_user = BookUser.find_by(id: params[:id])
    user_to_remove = book_user.user
    book_to_remove = book_user.book
    if book_user.user_id == user.id
      book_user.destroy
      flash[:success] = "Book successfully removed."
    elsif user_to_remove.owns_book?(book_to_remove)
      flash[:error] = "You cannot remove a book from a user who owns the book."
    elsif user.owns_book?(book_to_remove)
      book_user.destroy
      flash[:success] = "Successfully removed the user from the book."
    else
      flash[:error] = "You cannot remove a user from a book you do not own."
    end
    redirect_to books_path, status: :see_other
  end

  def switch_is_public # POST /books/:book_id/public
    user = current_user
    book = user.books.find_by(id: params[:book_id])
    if user.owns_book?(book)
      book.is_public = !book.is_public
      book.save
      flash[:success] = "Book successfully made public." if book.is_public
      flash[:success] = "Book successfully made private." unless book.is_public
    else
      flash[:error] = "You must be an owner of the book to change its public status."
    end
    redirect_to edit_book_path(book)
  end

  private

  def book_params
    params.require(:book).permit(:name, :description)
  end

  def book_user_params
    params.permit(:name, :book_id, :role_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_article_tree_part.html.erb
<li>
  <%= article.name %>
  <%= link_to "Edit", edit_book_article_path(@book, article), class: "pl-1 underline text-blue-600" %>
  <%= link_to "New subarticle", "/books/#{@book.id}/articles/#{article.id}/new", class: "underline text-blue-600" %>

  <% if article.has_children? %>
    <ul class="pl-4">
      <% article.subarticles.each do |subarticle| %>
        <%= render partial: 'article_tree_part', locals: {article: subarticle} %>
      <% end %>
    </ul>
  <% end %>
</li>

app/views/books/_editor_article_tree_part.html.erb
<li>
  <div class="flex justify-between items-center">

    <div class="flex flex-row items-center justify-start">
      <%= link_to article.name, edit_book_article_path(@book, article), class: "hover:bg-gray-100" %>
    
      <% if article.is_locked %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
        </svg>
      <% end %>
    </div>

    <div class="flex flex-row items-center">
      <a href="/books/<%= @book.id %>/articles/<%= article.id %>/new" class="text-xs rounded-md shadow-md p-1 ml-2 text-white bg-blue-600 hover:bg-blue-700">
        New subarticle
      </a>
      <form method="post" action="/books/<%= @book.id %>/articles/<%= article.id %>/lock">
        <button type="submit" class="text-xs rounded-md shadow-md p-1 ml-2 text-white bg-blue-600 hover:bg-blue-700">
          <% if article.is_locked %>
            Unlock article
          <% elsif !article.is_locked %>
            Lock article
          <% end %>
        </button>
      </form>
    </div>

  </div>
</li>

<% if article.has_children? %>
  <ul class="pl-4">
    <% article.subarticles.each do |subarticle| %>
      <%= render partial: 'editor_article_tree_part', locals: {article: subarticle} %>
    <% end %>
  </ul>
<% end %>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true, class: "bg-white p-4 border border-black" do |f| %>

  <% if @book.errors.any? %>
    <div>
      This form contains <%= pluralize(@book.errors.count, "error") %>.
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, class: "block" %>
  <%= f.text_field :name, class: "p-1 block bg-gray-100" %>

  <%= f.label :description, class: "block" %>
  <%= f.text_area :description, class: "p-1 block bg-gray-100 w-full" %>
  <div class="flex justify-center items-center">
  <%= f.submit class: "cursor-pointer bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2 mt-4" %>
  </div>
<% end %>

app/views/books/_reader_article_tree_part.html.erb
<li id="reader-article-part-for-article-with-id-<%= article.id %>" class="reader-article-tree-parts">
  <span class="hover:bg-gray-200 cursor-pointer"><%= article.name %></span>
</li>

<% if article.has_children? %>
  <ul class="pl-4">
    <% article.subarticles.each do |subarticle| %>
      <%= render partial: 'reader_article_tree_part', locals: {article: subarticle} %>
    <% end %>
  </ul>
<% end %>

app/views/books/_share_book_form.html.erb
<%= form_with url: bookuser_new_path, method: :post, class: "flex flex-col m-auto max-w-lg" do |form| %>

  <p>Enter the username (not email) of the user you would like to share this book with, and choose the role you would like the user to have for the book.</p>
  <p>Note that an owner will have equal permissions as you do (e.g. deleting the book). An editor will be able to add, edit, and delete articles of the book.</p>

  <input type="hidden" value="<%= @book.id %>" name="book_id">
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name, class: "border border-black" %>
  <div>
    <input type="radio" id="reader-role-radio-button" name="role_id" value="1" checked>
    <label for="reader-role-radio-button">Reader</label>
  </div>
  <div>
    <input type="radio" id="editor-role-radio-button" name="role_id" value="2">
    <label for="editor-role-radio-button">Editor</label>
  </div>
  <div>
    <input type="radio" id="owner-role-radio-button" name="role_id" value="3">
    <label for="owner-role-radio-button">Owner</label>
  </div>
  <%= form.submit "Submit", class: "cursor-pointer w-fit m-auto text-white rounded shadow bg-blue-600 mt-4 p-2" %>
<% end %>

app/views/books/edit.html.erb
<!-- Only editors and owners should be able to see this view -->
<div class="lg:flex lg:justify-start">
  <section class="p-4">
  <h1 class="text-2xl mb-4">Editing Book: '<%= @book.name %>'</h1>
    <div class="bg-white border border-black min-w-max p-4">
      <div class="flex items-center border-b border-black mb-4 pb-4">
        <h2 class="text-2xl">
          Edit or add articles:
        </h2>
        <%= link_to 'New top-level article', new_book_article_path(@book), class: "ml-4 bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2" %>
      </div>

      <ul>
        <% @book.top_level_articles.each do |top_level_article| %>
          <%= render partial: 'editor_article_tree_part', locals: {article: top_level_article} %>
        <% end %>
      </ul>
        
      
    </div>
  </section>
  
  <% if @user.owns_book?(@book) %>
    <section class="p-4">
      <h1 class="text-2xl mb-4">Book Details:</h1>
      <%= render partial: "form" %>
        
    </section>

    <% if @book.users.select { |user| @user != user }.count > 0 %>
    <section class="p-4">
      <h1 class="text-2xl mb-4">Other Book Users:</h1>
      
        <table class="table-auto bg-white border-collapse">
        <thead>
          <tr>
            <th class="border border-black p-1">Username</th>
            <th class="border border-black p-1">Role</th>
            <th class="border border-black p-1"></th>
          </tr>
        </thead>
        <tbody>
          <% @book.users.select {|user| user != @user }.each do |user| %>
            <tr>
              <td class="border border-black p-1"><%= user.name %></td>
              <td class="border border-black p-1"><%= @book.role(user) %></td>
              <td class="border border-black p-1">
                <%= link_to "Remove", "/bookuser/#{user.book_users.find_by(book_id: @book.id).id}", class: "text-red-600 underline", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
        </table>
      
    </section>
    <% end %>
  <% end %>
</div>

<div class="flex justify-start space-x-4 items-center p-4">
  <% if @user.owns_book?(@book) %>

    <button id="show-share-book-modal-btn" class="bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2">Share Book</button>

    <form action="/books/<%= @book.id %>/public" method="post">
      <button type="submit" class="bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2">
        <% if @book.is_public %>
          Make book private
        <% elsif !@book.is_public %>
          Make book public
        <% end %>
      </button>
    </form>

    
  <% end %>

    <%= link_to "Remove Book", "/bookuser/#{@user.book_users.find_by(book_id: @book.id).id}", class: "p-2 rounded-md bg-red-600 text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

</div>

<div class="flex justify-end">
  <%= link_to "Delete Book", book_path(@book), class: "p-2 rounded-md bg-red-600 text-white mt-8 mr-4", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</div>



<%= render partial: "share_book_form", layout: "shared/modal", locals: {label: "share-book"} %>

<% if @user.owns_book?(@book) %>
<script>
document.getElementById("show-share-book-modal-btn").addEventListener('click', function() {
  document.getElementById('share-book-modal').style.display = "block";
})

document.getElementById("share-book-modal-close-btn").addEventListener('click', function() {
  document.getElementById('share-book-modal').style.display = "none";
})

</script>
<% end %>

app/views/books/index.html.erb
<div class="p-4">

  <div class="flex justify-start items-center border-b border-black pb-4">
    <h1 class="text-4xl">
      Your Books:
    </h1>
    <a href="/books/new" class="ml-2 bg-blue-600 hover:bg-blue-700 rounded-md shadow-md text-white p-2">
      New book
    </a>
  </div>

  <ul class="mt-4">
    <% @books.each do |book| %>
      <li class="pb-4">
        <div class="flex justify-start items-center">
          <h3 class="text-2xl">
            <%= book.name %>
          </h3>

          <a class="text-md bg-blue-600 hover:bg-blue-700 text-white px-2 py-1 rounded-md shadow-md ml-4" href="/books/<%= book.id %>">
            Read
          </a>

          <% if @user.can_edit?(book) %>
            <a class="text-md bg-blue-600 hover:bg-blue-700 text-white px-2 py-1 rounded-md shadow-md ml-4" href="/books/<%= book.id %>/edit">
              Edit
            </a>
          <% else %>
            <%= link_to "Remove Book", "/bookuser/#{@user.book_users.find_by(book_id: book.id).id}", class: "text-md bg-red-600 text-white px-2 py-1 rounded-md ml-4", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
        </div>

        <ul class="list-inside list-disc">
          <li>
            <%= book.description %>
          </li>

          <li>
            <%= book.is_public ? "Public" : "Private" %>
          </li>

          <li>
            Your role: <%= book.role(@user) %>
          </lI>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/books/new.html.erb
<div class="p-4">
  <h1 class="text-2xl mb-4">New Book:</h1>
  <%= render 'form' %>
</div>

app/views/books/show.html.erb
<style>
.article-content-displayed h1, .article-content-displayed h2, .article-content-displayed h3, .article-content-displayed h4, .article-content-displayed h5, .article-content-displayed h6 {
  font-weight: 500;
  border-bottom: 1px solid gray;
}
.article-content-displayed h1 {
  font-size: 2.5rem;
}
.article-content-displayed h2 {
  font-size: 2.25rem;
}
.article-content-displayed h3 {
  font-size: 2rem;
}
.article-content-displayed h4 {
  font-size: 1.75rem;
}
.article-content-displayed h5 {
  font-size: 1.5rem;
}
.article-content-displayed h6 {
  font-size: 1.25rem;
}
.article-content-displayed .ankiNote {
  font-weight: 350;
}
.article-content-displayed img {
  padding: 1rem;
  margin: auto;
}
.article-content-displayed p {
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
}
</style>

<div class="lg:grid lg:grid-cols-4 min-h-screen">
  
  <div class="col-span-1 max-h-fit p-4 flex flex-col justify-start items-baseline">
    <div class="bg-white border border-black shadow-md rounded-md p-4">
      <h1 id="title-for-book-with-id-<%= @book.id %>" class="book-title text-center text-2xl border-b border-black pb-4 mb-4">
        <%= @book.name %>
      </h1>

      <ul>
        <% @book.top_level_articles.each do |top_level_article| %>
          <%= render partial: 'reader_article_tree_part', locals: {article: top_level_article} %>
        <% end %>
      </ul>
    </div>
    <a id="download-deck-button" href="" class="bg-blue-600 text-white rounded-md text-sm p-2 mt-1">Download deck</a>

  </div>

  <div id="article-content-div" class="article-content-displayed bg-white border col-span-3 border-black shadow-md rounded-md m-4 p-4">
    
  </div>

</div>